from django.test import TestCase
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from accounts.models import Token
User = get_user_model()


class UserModelTest(TestCase):

    def test_user_is_valid_with_email_only(self):
        user = User(email='a@b.com')
        user.full_clean()
    
    def test_user_is_invalid_with_email_only(self):
        user = User(email='a@#1!@!#sadsb..com')
        self.assertRaises(ValidationError, user.full_clean)
    
    def test_email_is_primary_key(self):
        user = User(email='a@b.com')
        self.assertEqual(user.pk, 'a@b.com')

class TokenModelTest(TestCase):

    def test_links_user_with_autogenerated_uid(self):
        token_1 = Token.objects.create(email='a@b.com')
        token_2 = Token.objects.create(email='a@b2.com')

        self.assertNotEqual(token_1.uid, token_2.uid)